import { useEffect, useRef, useState } from "react";
import { Sparkles, Loader2, X } from "lucide-react";
import { getConsent, onConsentChange } from "@/lib/cookieConsent";

const EXAMPLE_QUESTIONS = [
  "How much does an eye examination cost?",
  "Do you offer NHS eye tests?",
  "How is OCT different from a standard eye test?",
  "How long does it take to adjust to varifocals?",
];

export default function AskAI() {
  const [open, setOpen] = useState(false);
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  // Nudge the widget up while the cookie banner is still showing, so they don't overlap.
  const [cookieBannerVisible, setCookieBannerVisible] = useState(() => getConsent() === null);
  const panelRef = useRef<HTMLDivElement>(null);
  const launcherRef = useRef<HTMLButtonElement>(null);

  useEffect(() => onConsentChange(() => setCookieBannerVisible(false)), []);

  useEffect(() => {
    if (!open) return;
    const onClickOutside = (e: MouseEvent) => {
      const target = e.target as Node;
      if (panelRef.current?.contains(target) || launcherRef.current?.contains(target)) return;
      setOpen(false);
    };
    document.addEventListener("mousedown", onClickOutside);
    return () => document.removeEventListener("mousedown", onClickOutside);
  }, [open]);

  const ask = async (q: string) => {
    const trimmed = q.trim();
    if (!trimmed || loading) return;
    setLoading(true);
    setError(null);
    setAnswer(null);
    try {
      const res = await fetch("/api/ask", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question: trimmed }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error || "Something went wrong. Please try again.");
        return;
      }
      setAnswer(data.answer);
    } catch {
      setError("Something went wrong. Please check your connection and try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    ask(question);
  };

  return (
    <>
      <button
        ref={launcherRef}
        onClick={() => setOpen((o) => !o)}
        aria-label={open ? "Close AI assistant" : "Ask our AI assistant"}
        title={open ? "Close AI assistant" : "Ask our AI assistant"}
        aria-expanded={open}
        className={`fixed right-5 sm:right-6 z-40 w-14 h-14 rounded-full bg-[#1A2E45] text-[#F8F4EF] shadow-lg flex items-center justify-center hover:bg-[#1A2E45]/90 active:scale-95 transition-all duration-200 ${
          cookieBannerVisible ? "bottom-24" : "bottom-5 sm:bottom-6"
        }`}
      >
        {open ? <X className="w-5 h-5" /> : <Sparkles className="w-5 h-5" />}
      </button>

      {open && (
        <div
          ref={panelRef}
          className={`fixed right-5 sm:right-6 z-40 w-[calc(100vw-2.5rem)] sm:w-96 max-h-[70vh] overflow-y-auto bg-[#1A2E45] rounded-2xl shadow-2xl p-6 space-y-5 ${
            cookieBannerVisible ? "bottom-[10.5rem]" : "bottom-24"
          }`}
        >
          <div className="flex items-center justify-between gap-2.5">
            <div className="flex items-center gap-2.5">
              <Sparkles className="w-5 h-5 text-[#C9A96E]" />
              <h2
                className="text-xl font-light text-[#F8F4EF]"
                style={{ fontFamily: "'Cormorant Garamond', serif" }}
              >
                Ask our AI assistant
              </h2>
            </div>
            <span className="text-[9px] uppercase tracking-[0.15em] text-[#C9A96E]/80 border border-[#C9A96E]/30 rounded-full px-2 py-1 shrink-0">
              AI
            </span>
          </div>
          <p className="text-[#F8F4EF]/60 text-xs font-light leading-relaxed">
            Answers are generated by AI from our website content, so they may not always be perfect. For anything
            specific to your own eyes or prescription, please book an appointment or contact us directly.
          </p>

          <form onSubmit={handleSubmit} className="flex flex-col gap-3">
            <input
              type="text"
              autoFocus
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              placeholder="e.g. How much does an eye test cost?"
              className="w-full px-4 py-3 rounded-full bg-[#F8F4EF]/10 text-[#F8F4EF] placeholder:text-[#F8F4EF]/40 border border-[#F8F4EF]/15 focus:outline-none focus:border-[#C9A96E] transition-colors text-sm"
            />
            <button
              type="submit"
              disabled={loading || !question.trim()}
              className="px-6 py-3 bg-[#C9A96E] text-[#1A2E45] text-sm font-semibold tracking-wide rounded-full hover:bg-[#C9A96E]/90 active:scale-[0.97] transition-all duration-150 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {loading && <Loader2 className="w-4 h-4 animate-spin" />}
              {loading ? "Thinking..." : "Ask"}
            </button>
          </form>

          {!answer && !loading && !error && (
            <div className="flex flex-wrap gap-2">
              {EXAMPLE_QUESTIONS.map((q) => (
                <button
                  key={q}
                  onClick={() => {
                    setQuestion(q);
                    ask(q);
                  }}
                  className="px-3 py-1.5 rounded-full border border-[#F8F4EF]/15 text-[#F8F4EF]/70 text-xs hover:border-[#C9A96E]/50 hover:text-[#F8F4EF] transition-colors"
                >
                  {q}
                </button>
              ))}
            </div>
          )}

          {error && (
            <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/20 text-[#F8F4EF]/80 text-sm">
              {error}
            </div>
          )}

          {answer && (
            <div className="p-4 rounded-lg bg-[#F8F4EF]/5 border border-[#F8F4EF]/10 text-[#F8F4EF]/90 text-sm leading-relaxed">
              {answer}
            </div>
          )}
        </div>
      )}
    </>
  );
}
